COPY --from=builder /app/package.json .
RUN npm install --production --force

# 정적 파일을 서빙할 간단한 서버 설치
RUN npm install -g serve

# 서버 설정 파일 추가
COPY serve.json .

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000", "--config", "serve.json"]

# serve.json
{
  "rewrites": [
    { "source": "/images/*", "destination": "/images/:splat" },
    { "source": "/**", "destination": "/index.html" }
  ]
}