version: '3'

services:
  whitebox-ai:
    container_name: whitebox-ai
    build:
      context: .
      dockerfile: Dockerfile      
    environment:
      WORKERS_PER_CORE: "0.125"     #https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi
      LOG_LEVEL: "debug"      # debug|info|warning|error|critical      
      IS_DEBUG: false
      API_KEY: 22222222-2222-2222-2222-222222222222
      DATA_PATH: /app/data/
      APPLICATION_INSIGHTS_KEY: 11111111-1111-1111-1111-111111111111
    ports:
      - "5000:80"    
    volumes:
      - ./data:/app/data
    