spring.application.name=whitebox
spring.profiles.active=local
spring.jackson.serialization.WRITE_ENUMS_USING_TO_STRING=true

# Multipart File Setting
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# FFmpeg Setting
ffmpeg.path=C:\\Program Files\\ffmpeg-7.0.2-essentials_build\\bin\\ffmpeg.exe

# FastAPI Setting
fastapi.server.url=http://localhost:8000

# Upload Place
#file.upload-dir.images=backend/whitebox/src/main/resources/static/images
#file.upload-dir.videos=backend/whitebox/src/main/resources/static/videos
#file.upload-dir.thumbnails=backend/whitebox/src/main/resources/static/thumbnails
file.upload-dir.images=frontend/public/images
file.upload-dir.videos=frontend/public/videos
file.upload-dir.thumbnails=frontend/public/thumbnails
# Logging
logging.level.org.springframework.web.reactive.function.client=DEBUG

# JPA Setting
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# chatGPT Setting
spring.ai.openai.api-key=sk-handimap-o6MiaiAVqIBb96Ewm0ecT3BlbkFJZ7mrZRyxtwoGa5beVdfl

# JWT Setting
spring.jwt.secret = {tNrc]$eqwTq?bh[xS{qI.ST!VJ|'7>N+|(+(w9z0Qm7io'Ln}cx},W,F{'HZhc