spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql:3306/whitebox?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=ssafy

file.upload-dir.images=/etc/upload/images
file.upload-dir.videos=/etc/upload/videos
file.upload-dir.thumbnails=/etc/upload/thumbnails
