spring.application.name=whitebox
spring.profiles.active=local
spring.jackson.serialization.WRITE_ENUMS_USING_TO_STRING=true

# Multipart File Setting
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# FFmpeg Setting
ffmpeg.path=C:\\Program Files\\ffmpeg-7.0.2-essentials_build\\bin\\ffmpeg.exe

# FastAPI Setting
fastapi.server.url=http://localhost:8000



# Logging
logging.level.org.springframework.web.reactive.function.client=DEBUG

# JPA Setting
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# chatGPT Setting
spring.ai.openai.api-key=sk-handimap-o6MiaiAVqIBb96Ewm0ecT3BlbkFJZ7mrZRyxtwoGa5beVdfl

# JWT Setting
spring.jwt.secret = {tNrc]$eqwTq?bh[xS{qI.ST!VJ|'7>N+|(+(w9z0Qm7io'Ln}cx},W,F{'HZhc

# S3 Setting
cloud.aws.credentials.access-key=AKIARNR4S5T5AKUGEZ72
cloud.aws.credentials.secret-key=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
cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=whitebox-lawyer-vertify
